name: pytest-coverage

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Install dependencies
        run: |
          pip install pytest-cov
      - name: Get Coverage Report
        run: |
          ls
          pytest --cov=../ --cov-report=xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:      
          fail_ci_if_error: true
